### ISSUE TITLE
Window closed when leaving nvim

### ISSUE THREAD

**Issue by svenXY** [taylorzr/kitty-meow#4]
In addition to #2, if one uses nvim and closes it, then the window gets closed, and since #3 exists, the whole tab/session/project gets closed.

Is there any possibility to keep the tab/session/project open after having closed nvim?

**Comment by taylorzr** [comment]
Fixed in a branch. It uses env EDITOR instead of always nvim, and closing the editor won't exit the kitty window.

I'll get it merged eventually, but you can try with
```
cd ~/.config/kitty/meow && git fetch && git checkout some_tweaks
```

fix jfyi https://github.com/taylorzr/kitty-meow/compare/some_tweaks?expand=1#diff-cb57ee3fa612c16ed0cd99341111ec4c41689e5b15b8075d35d0c1679af44b1eR138-R154
